//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace country_club
{
    using System;
    using System.Collections.Generic;
    
    public partial class fiesta_invitado
    {
        public int id { get; set; }
        public string codfiesta { get; set; }
        public string tipoid { get; set; }
        public string identificacion { get; set; }
        public bool pagado { get; set; }
        public bool entradaptadorhuella { get; set; }
        public bool entradamanual { get; set; }
    }
}
