//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace country_club
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class countryEntities : DbContext
    {
        public countryEntities()
            : base("name=countryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<fiesta> fiesta { get; set; }
        public DbSet<fiesta_invitado> fiesta_invitado { get; set; }
        public DbSet<invitados> invitados { get; set; }
        public DbSet<socios> socios { get; set; }
    }
}
