//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace country_club
{
    using System;
    using System.Collections.Generic;
    
    public partial class socios
    {
        public int idsocio { get; set; }
        public string tipoid { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string identificacion { get; set; }
        public int numaccion { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public System.DateTime fechanac { get; set; }
        public string sexo { get; set; }
        public string correo { get; set; }
        public bool activo { get; set; }
    }
}
